[package]
name = "react_ssr"
version = "0.1.0"
authors = ["Valerio <valerioageno@yahoo.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty_v8 = "0.21.0"

[dev-dependencies]
actix-web = "3"
futures = "0.3.13"

[lib]
name = "react_ssr"
path = "src/lib.rs"

[[example]]
name = "actix"
path = "examples/actix.rs"